
CREATE TABLE IF NOT EXISTS users(
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(190) UNIQUE,
  password VARCHAR(255),
  role VARCHAR(50) DEFAULT 'admin',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS settings(
  `key` VARCHAR(120) PRIMARY KEY,
  `value` MEDIUMTEXT
);
CREATE TABLE IF NOT EXISTS hero_slides(
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200), subtitle VARCHAR(300),
  button_text VARCHAR(100), button_link VARCHAR(300),
  image VARCHAR(200), enabled TINYINT DEFAULT 1,
  sort_order INT DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS brands(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200), logo VARCHAR(200), enabled TINYINT DEFAULT 1, sort_order INT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS accessories(
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200), description VARCHAR(400), image VARCHAR(200), enabled TINYINT DEFAULT 1
);
CREATE TABLE IF NOT EXISTS offers(
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200), copy VARCHAR(500), image VARCHAR(200),
  valid_from DATE NULL, valid_to DATE NULL, enabled TINYINT DEFAULT 1
);
