
-- Dalmia CMS schema (expanded)
CREATE TABLE IF NOT EXISTS dc_settings (
  id INT PRIMARY KEY AUTO_INCREMENT,
  k VARCHAR(160) UNIQUE,
  v LONGTEXT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dc_pages (
  id INT PRIMARY KEY AUTO_INCREMENT,
  slug VARCHAR(160) UNIQUE,
  title VARCHAR(200),
  description VARCHAR(300),
  content LONGTEXT,
  schema_json LONGTEXT,
  blocks JSON,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dc_leads (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120), phone VARCHAR(40), email VARCHAR(160),
  interest VARCHAR(80), message TEXT, source VARCHAR(80),
  meta JSON, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dc_jobs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  role VARCHAR(160), department VARCHAR(120), location VARCHAR(120),
  type VARCHAR(80), description LONGTEXT, status ENUM('open','closed') DEFAULT 'open',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dc_applications (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  job_id BIGINT, name VARCHAR(120), phone VARCHAR(40), email VARCHAR(160), experience TEXT,
  why_join TEXT, cv_path VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dc_reviews_curated (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  author VARCHAR(160), rating TINYINT, text TEXT, source VARCHAR(80), avatar_url VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
